$skillsRoot = "C:\Users\Admin\Desktop\tools\dev-bootstrap\skills"
$outputPath = "C:\Users\Admin\Desktop\tools\dev-bootstrap\SKILLS.md"

$files = Get-ChildItem -LiteralPath $skillsRoot -Recurse -File -Filter "SKILL.md" | Sort-Object FullName

$lines = @()
$lines += "# dev-bootstrap Skills Manifest"
$lines += ""
$lines += "All $($files.Count) skills shipped with dev-bootstrap v0.1.0."
$lines += "Each skill lives in its own directory: 'skill-name/SKILL.md'."
$lines += "Installed at setup time to: `%USERPROFILE%\.opencode\skills\` (follows junction if present)."
$lines += ""
$lines += "---"
$lines += ""

$currentDir = $null
foreach ($f in $files) {
    $relative = $f.FullName.Substring($skillsRoot.Length).TrimStart('\', '/')
    $parentDir = Split-Path -Parent $relative
    $content = Get-Content -LiteralPath $f.FullName -Raw

    $name = $null
    $description = $null
    if ($content -match "(?ms)^---\s*\nname:\s*(.+?)\s*\n.*?description:\s*(.+?)\s*\n") {
        $name = $Matches[1].Trim().Trim('"', "'")
        $description = $Matches[2].Trim().Trim('"', "'")
    }

    $displayDir = if ($parentDir -eq "") { "(root)" } else { $parentDir }

    if ($displayDir -ne $currentDir) {
        $currentDir = $displayDir
        $lines += ""
        $lines += "## $displayDir"
        $lines += ""
    }

    if ($name -and $description) {
        $firstLine = ($description -split "`n")[0].Trim()
        $lines += "- **$name** - $firstLine"
        $lines += "  - path: '" + $relative + "'"
    } else {
        $lines += "- (could not parse frontmatter) - path: '" + $relative + "'"
    }
}

$lines += ""
$lines += "---"
$lines += ""
$lines += "_Auto-generated by 'tools/generate-skills-manifest.ps1'. Re-run after updating skills/._"

$content = ($lines -join "`n")
Set-Content -LiteralPath $outputPath -Value $content -Encoding UTF8
Write-Host "Wrote $($files.Count) skills to $outputPath"
Write-Host "Size: $([math]::Round((Get-Item $outputPath).Length / 1KB, 1)) KB"
