# Auto-generates SKILLS.md from the skills/ tree.
#
# Agnostic by design: all paths default to locations relative to this script
# (via $PSScriptRoot), so the file works from any clone of dev-bootstrap --
# no hardcoded absolute paths to one developer's machine.
#
# The manifest renderer is exposed as a function so tests can dot-source this
# file and call it against synthetic trees. When invoked directly (not
# dot-sourced), the script runs the function with the default paths.

[CmdletBinding()]
param(
    [string]$RepoRoot,
    [string]$SkillsRoot,
    [string]$OutputPath
)

function Read-RepoVersion {
    # Reads the version string from <RepoRoot>/version.txt. Returns "unknown"
    # if the file is missing or empty, so callers never have to handle nulls.
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$RepoRoot)

    $versionFile = Join-Path $RepoRoot "version.txt"
    if (-not (Test-Path -LiteralPath $versionFile)) {
        return "unknown"
    }
    $raw = Get-Content -LiteralPath $versionFile -Raw
    $firstLine = ($raw -split "`r?`n")[0].Trim()
    if ([string]::IsNullOrWhiteSpace($firstLine)) {
        return "unknown"
    }
    return "v$firstLine"
}

function New-SkillsManifest {
    # Renders the skills manifest to a Markdown file. Validates inputs and
    # fails loud (throws) on any structural problem -- the contract is "no
    # silent partial output".
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][string]$SkillsRoot,
        [Parameter(Mandatory)][string]$OutputPath
    )

    if (-not (Test-Path -LiteralPath $RepoRoot)) {
        throw "RepoRoot not found: $RepoRoot"
    }
    if (-not (Test-Path -LiteralPath $SkillsRoot)) {
        throw "SkillsRoot not found: $SkillsRoot (expected the skills/ tree)"
    }
    $outputDir = Split-Path -Parent $OutputPath
    if (-not (Test-Path -LiteralPath $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }

    $version = Read-RepoVersion -RepoRoot $RepoRoot
    $files = Get-ChildItem -LiteralPath $SkillsRoot -Recurse -File -Filter "SKILL.md" | Sort-Object FullName

    $lines = @()
    $lines += "# dev-bootstrap Skills Manifest"
    $lines += ""
    $lines += "All $($files.Count) skills shipped with dev-bootstrap $version."
    $lines += "Each skill lives in its own directory: 'skill-name/SKILL.md'."
    $lines += "Installed at setup time to: `%USERPROFILE%\.opencode\skills\` (follows junction if present)."
    $lines += ""
    $lines += "---"
    $lines += ""

    $currentDir = $null
    foreach ($f in $files) {
        $relative = $f.FullName.Substring($SkillsRoot.Length).TrimStart('\', '/')
        $parentDir = Split-Path -Parent $relative
        $content = Get-Content -LiteralPath $f.FullName -Raw

        $name = $null
        $description = $null
        if ($content -match "(?ms)^---\s*\nname:\s*(.+?)\s*\n.*?description:\s*(.+?)\s*\n") {
            $name = $Matches[1].Trim().Trim('"', "'")
            $description = $Matches[2].Trim().Trim('"', "'")
        }

        $displayDir = if ($parentDir -eq "") { "(root)" } else { $parentDir }

        if ($displayDir -ne $currentDir) {
            $currentDir = $displayDir
            $lines += ""
            $lines += "## $displayDir"
            $lines += ""
        }

        if ($name -and $description) {
            $firstLine = ($description -split "`n")[0].Trim()
            $lines += "- **$name** - $firstLine"
            $lines += "  - path: '" + $relative + "'"
        } else {
            $lines += "- (could not parse frontmatter) - path: '" + $relative + "'"
        }
    }

    $lines += ""
    $lines += "---"
    $lines += ""
    $lines += "_Auto-generated by 'tools/generate-skills-manifest.ps1'. Re-run after updating skills/._"

    $rendered = ($lines -join "`n")
    # -NoNewline: match Render-Config's idempotency-friendly write so byte
    # comparisons stay predictable across PS 5.1 and 7+.
    Set-Content -LiteralPath $OutputPath -Value $rendered -Encoding UTF8 -NoNewline
    Write-Host "Wrote $($files.Count) skills to $OutputPath"
    Write-Host "Size: $([math]::Round((Get-Item $OutputPath).Length / 1KB, 1)) KB"
}

# Run only when invoked directly (not dot-sourced by tests). Using
# $MyInvocation.InvocationName is the standard PS 5.1+ idiom to detect this.
if ($MyInvocation.InvocationName -ne '.') {
    # Resolve script-relative defaults in the body, not the param block.
    # PowerShell evaluates param defaults BEFORE $PSScriptRoot is bound, so
    # default expressions like `Split-Path -Parent $PSScriptRoot` produce
    # empty strings when the file is invoked as `-File`. The body sees the
    # real value. Fill in any unset / empty params with script-relative paths.
    $scriptRoot = $PSScriptRoot
    if ([string]::IsNullOrEmpty($RepoRoot))   { $RepoRoot   = Split-Path -Parent $scriptRoot }
    if ([string]::IsNullOrEmpty($SkillsRoot)) { $SkillsRoot = Join-Path (Split-Path -Parent $scriptRoot) "skills" }
    if ([string]::IsNullOrEmpty($OutputPath)) { $OutputPath = Join-Path (Split-Path -Parent $scriptRoot) "SKILLS.md" }
    New-SkillsManifest -RepoRoot $RepoRoot -SkillsRoot $SkillsRoot -OutputPath $OutputPath
}
